version: 2
builds:
  - binary: fabio
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
archives:
  - id: bin
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}'
    formats:
      - binary
changelog:
  use: github
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{.Version }}.src'
  prefix_template: '{{ .ProjectName }}-{{.Version }}/'
checksum:
  name_template: '{{.ProjectName}}-{{.Version}}.sha256'
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
dockers_v2:
  - dockerfile: Dockerfile-goreleaser
    images:
      - 'fabiolb/fabio'
    tags:
      - 'latest-{{ .Runtime.Goarch }}'
      - '{{ .Version }}-{{ .Runtime.Goarch }}'
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    annotations:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    extra_files:
      - fabio.properties
